# Generated by Django 3.1.5 on 2021-01-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='choreographer',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='matching',
            name='mentor',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='matching',
            name='student',
            field=models.BooleanField(default='False'),
        ),
    ]
