# Generated by Django 3.1.5 on 2021-01-14 19:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20210114_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Contemporary', 'Contemporary'), ('Folkloric', 'Folkloric'), ('Hip-hop', 'Hip-hop'), ('None', 'None')], default='None', max_length=35),
        ),
    ]
