# Generated by Django 3.1.5 on 2021-01-14 19:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_matching_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='choreography',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Contemporary', 'Contemporary'), ('Folkloric', 'Folkloric'), ('Hip-hop', 'Hip-hop'), ('None', 'None')], default='None', max_length=35),
        ),
        migrations.AddField(
            model_name='matching',
            name='learning',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Contemporary', 'Contemporary'), ('Folkloric', 'Folkloric'), ('Hip-hop', 'Hip-hop'), ('None', 'None')], default='None', max_length=35),
        ),
    ]
