# Generated by Django 3.1.5 on 2021-01-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_auto_20210114_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matching',
            old_name='choreography',
            new_name='choreography_pref',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='learning',
            new_name='learning_pref',
        ),
    ]
