# Generated by Django 3.1.5 on 2021-01-14 21:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20210114_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='choreographer',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='student',
        ),
        migrations.AddField(
            model_name='matching',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Student', 'Student'), ('Mentor', 'Mentor'), ('Choreographer', 'Choreographer')], default='None', max_length=28),
        ),
    ]
