# Generated by Django 3.1.5 on 2021-01-14 22:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_auto_20210114_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mentor', 'Mentor'), ('Choreographer', 'Choreographer'), ('Student', 'Student')], default='None', max_length=28),
        ),
    ]
