# Generated by Django 3.1.5 on 2021-01-14 22:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_auto_20210114_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Student', 'Student'), ('Mentor', 'Mentor'), ('Choreographer', 'Choreographer')], default='None', max_length=28),
        ),
    ]
