# Generated by Django 3.1.5 on 2021-01-15 05:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_auto_20210114_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mentor', 'Mentor'), ('Student', 'Student'), ('Choreographer', 'Choreographer')], default='None', max_length=28),
        ),
    ]
